//This file is automatically generated by CMAKE. DO NOT MODIFY.
using System;

namespace Emgu.CV
{
   public partial class CvInvoke
   {
      /// <summary>
      /// The file name of the core library
      /// </summary>
      public const string OPENCV_CORE_LIBRARY = "opencv_core242";
      /// <summary>
      /// The file name of the imgproc library
      /// </summary>
      public const string OPENCV_IMGPROC_LIBRARY = "opencv_imgproc242";
      /// <summary>
      /// The file name of the highgui library
      /// </summary>
      public const string OPENCV_HIGHGUI_LIBRARY = "opencv_highgui242";
	  /// <summary>
      /// The file name of the flann library
      /// </summary>
      public const string OPENCV_FLANN_LIBRARY = "opencv_flann242";
      /// <summary>
      /// The file name of the feature2d library
      /// </summary>
      public const string OPENCV_FEATURES2D_LIBRARY = "opencv_features2d242";
      /// <summary>
      /// The file name of the objdetect library
      /// </summary>
      public const string OPENCV_OBJDETECT_LIBRARY = "opencv_objdetect242";
      /// <summary>
      /// The file name of the calib3d library
      /// </summary>
      public const string OPENCV_CALIB3D_LIBRARY = "opencv_calib3d242";
      /// <summary>
      /// The file name of the legacy library
      /// </summary>
      public const string OPENCV_LEGACY_LIBRARY = "opencv_legacy242";
      /// <summary>
      /// The file name of the video library
      /// </summary>
      public const string OPENCV_VIDEO_LIBRARY = "opencv_video242";
      /// <summary>
      /// The file name of the gpu library
      /// </summary>
      public const string OPENCV_GPU_LIBRARY = "opencv_gpu242";
	  /// <summary>
      /// The file name of the opencv_stitching library
      /// </summary>
      public const string OPENCV_STITCHING_LIBRARY = "opencv_stitching242";
      /// <summary>
      /// The file name of the cvextern library
      /// </summary>
      public const string EXTERN_LIBRARY = "cvextern";
      /// <summary>
      /// The file name of the cvextern_gpu library
      /// </summary>
      public const string EXTERN_GPU_LIBRARY = "cvextern";
      /// <summary>
      /// The file name of the opencv_ffmpeg library
      /// </summary>
      public const string OPENCV_FFMPEG_LIBRARY = "opencv_ffmpeg242_64";
	  /// <summary>
      /// The file name of the ml library
      /// </summary>
      public const string OPENCV_ML_LIBRARY = "opencv_ml242";
	  /// <summary>
      /// The file name of the contrib library
      /// </summary>
      public const string OPENCV_CONTRIB_LIBRARY = "opencv_contrib242";
	  /// <summary>
      /// The file name of the photo library
      /// </summary>
      public const string OPENCV_PHOTO_LIBRARY = "opencv_photo242";
	  /// <summary>
      /// The file name of the nonfree library
      /// </summary>
      public const string OPENCV_NONFREE_LIBRARY = "opencv_nonfree242";
	  /// <summary>
      /// The file name of the videostab library
      /// </summary>
      public const string OPENCV_VIDEOSTAB_LIBRARY = "opencv_videostab242";
	  
      /// <summary>
      /// The bit-ness of the unmanaged code (either 32 or 64) 
      /// </summary>
      public const uint UnmanagedCodeBitness = 64;
   }
}
